아무런정보도 없이 예약이되는 현상을 방지하기위한 button disabled 처리를 하라
CodeSoom-Project/my-seat pull request #206
Opened 2022-10-13 16:16 UTC by alstjr0183

현재는 아무정보를 입력하지않아도 제출을 할수있습니다
그것을 방지하기위해 예약모달에서 날짜와 계획을 입력한경우만 제출할수있도록 작업했습니다

2022-10-13 16:47 UTC, hannut91 commented
> 아무입력없이 예약,회고가 제출되는 현상을 방지하기위한 button disabled 처리를 하라

이건 한 일입니다. 

저라면 

> 예약, 회고 작성할 때 필수 입력 항목 빠트렸는지 검사하라

이렇게 쓸 것 같아요

2022-10-13 16:49 UTC, hannut91 requested changes

2022-10-13 16:49 UTC, hannut91 commented on app-web/src/components/reservation/ReservationDialog.tsx
> +        <Button disabled={!(date && plan)} variant="contained" size="small">
`!data || !plan`이 더 이해하기 쉬울 것 같아요

2022-10-13 16:49 UTC, hannut91 commented on app-web/src/pages/Retrospection/RetrospectionModal.tsx
> +  const isMinimum = retrospections.length > 100;
100이 아니라 50으로 변경하기로 했다고 합시다. 그러면 변경되어야 하는 코드가 어디어디 일까요?

2022-10-14 00:59 UTC, alstjr0183 commented on app-web/src/components/reservation/ReservationDialog.tsx
> +        <Button disabled={!(date && plan)} variant="contained" size="small">
수정했습니다 

date ,plan을 읽고 !로 확인까지해야 알수있는거보단
!date , || , !plan 하나하나읽을수있는 표현이 더 이해하기가쉽군요!

2022-10-14 01:27 UTC, alstjr0183 commented on app-web/src/pages/Retrospection/RetrospectionModal.tsx
> +  const isMinimum = retrospections.length > 100;
50으로 변경된다면 TextField에 minLegth도 수정해줘야했습니다

변수로 담아서 관리하게끔 수정했습니다

2022-10-14 01:40 UTC, hannut91 approved these changes

2022-10-14 01:40 UTC, hannut91 commented on app-web/src/pages/Retrospection/RetrospectionModal.tsx
> +  const characterLimit = 1000;
위에 변수를 Minimum으로 썼으니, Limit도 Maximum으로 쓰면 일관성이 있을 것 같아요

2022-10-14 01:46 UTC, alstjr0183 commented on app-web/src/pages/Retrospection/RetrospectionModal.tsx
> +  const characterLimit = 1000;
수정했습니다!

2022-10-14 01:49 UTC, merged