회고 작성이 완료가 되면 예약 상태의 회고작성 전을 회고작성 완료 변경하라
CodeSoom-Project/my-seat pull request #253
Opened 2022-10-18 13:05 UTC by jihwooon

회고 예약 목록을 조회를 할 때 회고작성 전하고 회고작성 후에 따라 상태가 나와야 합니다. 
프론트에서는 이 상태값에 따라 함수가 실행이 된다고 하기에 회고 작성 후 회고작성 후로 상태값이 변경 되어야 합니다.

2022-10-18 21:52 UTC, JIY0UNG approved these changes

2022-10-19 01:53 UTC, hannut91 requested changes

2022-10-19 01:53 UTC, hannut91 commented on app-server/app/src/main/java/com/codesoom/myseat/domain/Reservation.java
> +    }
메서드 이름에 이 메서드가 무엇을 하는지 전부 드러나고 있습니다. 무엇을 하는지 보다 의도를 드러내 주세요

2022-10-19 01:53 UTC, hannut91 commented on app-server/app/src/main/java/com/codesoom/myseat/services/reservations/retrospectives/RetrospectiveService.java
> +        return retrospectiveRepository.save(retrospective);
이건 왜 생긴거예요?

2022-10-19 01:53 UTC, hannut91 commented on app-server/app/src/test/java/com/codesoom/myseat/services/reservations/retrospectives/RetrospectiveServiceTest.java
> +    }
이건 무엇을 테스트하는지 잘 모르겠습니다

2022-10-19 01:53 UTC, hannut91 commented on app-server/http-request/local/회고작성.http
> +POST http://localhost:8080/reservations/2/retrospectives
이건 왜 바뀐건지 잘 모르겠습닌다

2022-10-20 01:59 UTC, hannut91 requested changes

2022-10-20 01:59 UTC, hannut91 commented on app-server/app/src/main/java/com/codesoom/myseat/domain/Reservation.java
> +    }
이 함수가 무엇을 하는건지 의도가 드러나지 않습니다. 왜 이 함수를 호출해야 하나요?

2022-10-20 01:59 UTC, hannut91 commented on app-server/app/src/main/java/com/codesoom/myseat/domain/Retrospective.java
> +    }
createRetrospective가 Reservation와 content를 받아서 Restrospective를 반환한다는 함수의 Signature만 봐도 이해하기 어렵습니다. 의도가 무엇인지 알기 어렵습니다.

심지어 안에서는 reservation을 변경하고 있는데, 변경이 되는건지 의도를 알기 어렵습니다.

2022-10-20 04:26 UTC, jihwooon commented on app-server/app/src/main/java/com/codesoom/myseat/domain/Reservation.java
> +    }
회고 작성이 완료가 되면 회고 작성 전 상태에서 회고 작성 완료를 위해서 메서드를 생성했습니다.

2022-10-20 04:29 UTC, JIY0UNG commented on app-server/app/src/main/java/com/codesoom/myseat/domain/Reservation.java
> +    }
윤석님 말씀은 함수명에 의도가 드러나있지 않다는 뜻인 것 같아요

2022-10-20 04:32 UTC, JIY0UNG commented on app-server/app/src/main/java/com/codesoom/myseat/domain/Reservation.java
> +    }
앗 지환님 댓글이 사라졌네요

2022-10-20 05:11 UTC, hannut91 commented on app-server/app/src/main/java/com/codesoom/myseat/domain/Reservation.java
> +    }
굳

2022-10-20 05:11 UTC, hannut91 commented on app-server/app/src/main/java/com/codesoom/myseat/services/reservations/retrospectives/RetrospectiveService.java
> +
이건 뭔가요?

2022-10-20 08:13 UTC, merged