토큰이 만료되었을때 다시 로그인하게 하라
CodeSoom-Project/my-seat pull request #267
Opened 2022-10-20 01:39 UTC by alstjr0183

토큰이 만료되었을때 다시 로그인하게끔 alert를 보여주는 작업을했습니다

토큰만료를 확인할수있는 state , 상태를변경시킬수있는 action을 만들었습니다
axios instance를 이용해서 401에러가났을때 토큰만료state를 변경시키는 action을 실행시켰습니다
토큰만료시 나오는 alert를 만들고 확인을 누르면 리덕스토큰제거, 스토리지토큰제거, 토큰상태를확인하는상태변경, url이동 작업을하게끔했습니다

![Oct-20-2022 10-33-17](https://user-images.githubusercontent.com/57708817/196835425-a722a001-f0d8-4ac8-a54b-6ede4628a36d.gif)

2022-10-20 01:42 UTC, alstjr0183 commented
axios 성공시 기존에 response.data 를 { data } 구조분해할당을통해 넘겨줬던 함수들을 
instance로 통일시키며 response만을 받게끔변경했습니다 
그로인해 기존에 react query통해 받아오던 로직을 data 에서 data.data로 접근하게끔 변경했습니다

기존
<img width="434" alt="image" src="https://user-images.githubusercontent.com/57708817/196836245-02f3e73e-4cdd-4384-9711-e177eb8d1cb0.png">

변경후
<img width="365" alt="image" src="https://user-images.githubusercontent.com/57708817/196836091-a2eab88d-7ade-44be-ac7d-04e93cb90b0c.png">

2022-10-20 01:51 UTC, hannut91 requested changes

2022-10-20 01:51 UTC, hannut91 commented on app-web/src/App.tsx
> +    dispatch(setIsTokenExpired(false));
이건 왜 하는건가요?

2022-10-20 01:51 UTC, hannut91 commented on app-web/src/App.tsx
> +      )}
다른 곳에서는 Dialog를 이렇게 사용하지 않습니다. 그리고 왜 Dialog를 사용하는지도 잘 모르겠습니다

2022-10-20 01:51 UTC, hannut91 commented on app-web/src/components/reservation/ReservationDialog.tsx
> +      <DateTitle>예약일 : {data?.data.date}</DateTitle>
왜 이렇게 쓰는건가요?

2022-10-20 01:51 UTC, hannut91 commented on app-web/src/services/api.ts
> +    return Promise.reject(error);
401의 경우를 처리했다면, reject하면 안될 것 같습니다

2022-10-20 02:13 UTC, alstjr0183 commented on app-web/src/services/api.ts
> +    return Promise.reject(error);
수정했습니다!

2022-10-20 04:23 UTC, Jongveloper commented on app-web/src/App.tsx
> +    dispatch(logout());
dispatch하는 리듀서 함수들이
전부 로그아웃기능을 담당하고 있어
한 리듀서 함수에서 처리하는 것이 어떨까요?
`localStrorage.removeItem()`도요!

2022-10-20 05:08 UTC, hannut91 requested changes

2022-10-20 05:08 UTC, hannut91 commented on app-web/src/services/api.ts
> +    return error;
왜 리턴하나요?

2022-10-20 12:38 UTC, alstjr0183 commented on app-web/src/App.tsx
> +    dispatch(setIsTokenExpired(false));
isTokenExpire 라는 state를 이용해서 토큰만료알림을 렌더링해주는데 로그아웃을 했을때 알림을 꺼주기 위해설정했었습니다

현재는 로그아웃시 새로고침을 통해 redux state를 다 없애주었으므로 삭제했습니다

2022-10-20 12:38 UTC, alstjr0183 commented on app-web/src/App.tsx
> +    dispatch(logout());
새로고침을 통해서 redux를 초기화시켜주어서 더이상 dispatch를 사용하지않게했습니다

2022-10-20 12:39 UTC, alstjr0183 commented on app-web/src/App.tsx
> +      )}
dialog의 open속성을 통해서 렌더링되게끔수정했습니다

2022-10-20 12:39 UTC, alstjr0183 commented on app-web/src/components/reservation/ReservationDialog.tsx
> +      <DateTitle>예약일 : {data?.data.date}</DateTitle>
수정했습니다

2022-10-20 12:39 UTC, alstjr0183 commented on app-web/src/services/api.ts
> +    return error;
수정했습니다

2022-10-21 00:30 UTC, hannut91 commented on app-web/src/App.tsx
> +      </Dialog>
컴포넌트로 분리하면 좋을 것 같아요

2022-10-21 00:30 UTC, hannut91 commented on app-web/src/authSlice.ts
>      },
이 reducer는 액션일까요 계산일까요

2022-10-21 01:32 UTC, alstjr0183 commented on app-web/src/authSlice.ts
>      },
localStorage를 사용함으로서 액션이였습니다
localStorage를 여기서 처리하지않고 다른 함수로 분리시켜 사용했습니다

2022-10-21 01:33 UTC, alstjr0183 commented on app-web/src/authSlice.ts
> +    },
수정했습니다

2022-10-21 01:34 UTC, alstjr0183 commented on app-web/src/App.tsx
> +      </Dialog>
Alert이라는 컴포넌트를 만들어 사용했습니다

2022-10-21 03:05 UTC, hannut91 commented on app-web/src/App.tsx
> +        text='토큰이 만료되었습니다. 다시로그인해주세요.'
"로 바꿔주세요

2022-10-21 03:05 UTC, hannut91 commented on app-web/src/App.tsx
> +    localStorage.removeItem('accessToken');
추상화 레벨이 안맞습니다

2022-10-21 03:05 UTC, hannut91 commented on app-web/src/authSlice.ts
> +  accessToken: string,
```suggestion
  isTokenExpired: boolean;

  accessToken: string;
```

2022-10-21 03:56 UTC, alstjr0183 commented on app-web/src/authSlice.ts
> +  accessToken: string,
수정했습니다

eslint로 관리할수있게끔하는 작업은 티켓으로 빼서 작업하겠습니다

2022-10-21 07:24 UTC, alstjr0183 commented on app-web/src/App.tsx
> +    localStorage.removeItem('accessToken');
수정했습니다

2022-10-21 07:26 UTC, alstjr0183 commented on app-web/src/App.tsx
> +        text='토큰이 만료되었습니다. 다시로그인해주세요.'
수정했습니다

2022-10-22 05:26 UTC, hannut91 commented on app-web/src/services/stoage.ts
> +
여기 빈 줄이 하나 더 들어간건가요?

2022-10-22 05:26 UTC, hannut91 commented on app-web/src/services/retrospectives.ts
> +  const { data } = await axios.get(`/reservations/${id}/retrospectives`, {
사용하는 사람이 `axios`원래 인스턴스랑 헷갈릴수도 있겠네요

2022-10-23 05:07 UTC, alstjr0183 commented on app-web/src/services/stoage.ts
> +
수정했습니다

2022-10-23 05:12 UTC, alstjr0183 commented on app-web/src/services/retrospectives.ts
> +  const { data } = await axios.get(`/reservations/${id}/retrospectives`, {
httpClient로 수정했습니다

2022-10-23 05:30 UTC, hannut91 approved these changes

2022-10-23 05:37 UTC, yerin512 approved these changes

2022-10-23 05:41 UTC, merged