회고를 수정 하라
CodeSoom-Project/my-seat pull request #277
Opened 2022-10-20 12:09 UTC by 0hu

회고 수정 기능작업을 했습니다.
회고 상세보기 화면에 수정버튼을 누르면 작성 모달로 변환됩니다.
수정버튼을 누르면 수정상태가 됩니다.
수정상태인 상태로 작성 모달에서 제출을 누르면 수정 api를 호출합니다.

2022-10-20 12:45 UTC, yerin512 commented on app-web/src/pages/Retrospectives/RetrospectivesModal.tsx
> +import { Button, CircularProgress, Dialog, DialogTitle, TextField } from '@mui/material';
한 줄 띄기 다시 해주시면 좋을 거 같습니다!

2022-10-20 12:45 UTC, yerin512 commented on app-web/src/pages/Retrospectives/RetrospectivesModal.tsx
> +      <TextBox>{data.content.split('\n').map((line: string) => (<p key={id}>{line}</p>))}</TextBox>
구조분해할당을 하는 건 어떨까요?

2022-10-20 12:45 UTC, yerin512 commented on app-web/src/pages/Retrospectives/RetrospectivesModal.tsx
>            <Button variant='outlined' size='small' onClick={onClose}>
이 부분도 한 줄띄기 하면 좋을거같습니다!

2022-10-21 00:40 UTC, hannut91 requested changes

2022-10-21 00:40 UTC, hannut91 commented on app-web/src/components/reservations/ReservationsTable.tsx
>                  }}>
핸들러 함수로 빼는게 좋아보입니다

2022-10-21 00:40 UTC, hannut91 commented on app-web/src/pages/Reservations.tsx
> +      onClicktoggleRetrospectModal();
camelCase로 작성해 주세요

2022-10-21 00:40 UTC, hannut91 commented on app-web/src/pages/Reservations.tsx
> +      content: retrospectives,
프론트에서도 `content`로 관리하면 좋을 것 같습니다

2022-10-21 00:40 UTC, hannut91 commented on app-web/src/pages/Retrospectives/RetrospectivesModal.tsx
> +    dispatch(saveIsUpdateRetrospectives(true));
상세인지 false로 하고 수정중인지 true로 업데이트하고 있는 것 같습니다. 상태를 나타내고 싶을 경우에는 상태를 만드는게 좋을 것 같아요. 예를들어 `UPDATE', `CREATE` 처럼 여러가지 상태를 나타낼 수 있는 상태값을 만들 수 있어요

2022-10-21 00:40 UTC, hannut91 commented on app-web/src/services/retrospectives.ts
> +  });
```suggestion
  return api.put(`/reservations/${id}/retrospectives`, { content }, {
    headers: { 
      Authorization: `Bearer ${accessToken}` 
    }
  });
```

2022-10-21 01:40 UTC, 0hu commented on app-web/src/pages/Retrospectives/RetrospectivesModal.tsx
> +      <TextBox>{data.content.split('\n').map((line: string) => (<p key={id}>{line}</p>))}</TextBox>
수정하였습니다.

2022-10-21 01:40 UTC, 0hu commented on app-web/src/pages/Retrospectives/RetrospectivesModal.tsx
>            <Button variant='outlined' size='small' onClick={onClose}>
수정하였습니다.

2022-10-21 01:48 UTC, 0hu commented on app-web/src/components/reservations/ReservationsTable.tsx
>                  }}>
리듀서 함수 saveIsUpdateRetrospectives 를 handleClickRetrospective에 포함시켰습니다.

2022-10-21 01:49 UTC, 0hu commented on app-web/src/pages/Reservations.tsx
> +      onClicktoggleRetrospectModal();
수정하였습니다.

2022-10-21 02:03 UTC, 0hu commented on app-web/src/pages/Reservations.tsx
> +      content: retrospectives,
사용 하는 곳이 많아 티켓으로 만들어 작업하겠습니다.

2022-10-21 02:18 UTC, 0hu commented on app-web/src/pages/Retrospectives/RetrospectivesModal.tsx
> +    dispatch(saveIsUpdateRetrospectives(true));
예약 , 회고 둘다 flag로 랜더링 하고 있기 때문에 티켓을 만들어 한번에 작업 을 하겠습니다.

2022-10-21 02:38 UTC, 0hu commented on app-web/src/services/retrospectives.ts
> +  });
수정하였습니다.

2022-10-21 10:42 UTC, hannut91 approved these changes

2022-10-21 10:56 UTC, merged