계획 내용 작성 시 글자수를 나타내라
CodeSoom-Project/my-seat pull request #293
Opened 2022-10-21 12:27 UTC by hxunz

계획 작성 시 작성한 글자수를 화면에 보여주도록 했습니다. 
<img width="473" alt="스크린샷 2022-10-21 오후 9 27 36" src="https://user-images.githubusercontent.com/77002038/197195572-41942617-c37b-445d-a220-73d01f7b322b.png">

2022-10-22 05:10 UTC, hannut91 requested changes

2022-10-22 05:10 UTC, hannut91 commented on app-web/src/components/reservation/ReservationDialog.tsx
> +          helperText={`${content.length} /${characterMaximum}`}
```suggestion
          helperText={`${content.length} / ${characterMaximum}`}
```

여기 빈 칸 띄어야 겠네요

2022-10-22 05:10 UTC, hannut91 commented on app-web/src/components/reservation/ReservationDialog.tsx
> +          inputProps={{ minLength: characterMaximum }}
최소 글자 수가 `characterMaximum` 이군요. 뭔가 잘못쓰신 것 같아요.

2022-10-23 14:16 UTC, Jongveloper commented on app-web/src/components/reservation/ReservationDialog.tsx
> +            닫기
띄어쓰기는 안해도 될 것 같아요!

2022-10-23 14:16 UTC, Jongveloper commented on app-web/src/components/reservation/ReservationDialog.tsx
> +            수정
여기두요!

2022-10-24 01:46 UTC, hxunz commented on app-web/src/components/reservation/ReservationDialog.tsx
> +          inputProps={{ minLength: characterMaximum }}
수정했습니다.

2022-10-24 01:46 UTC, hxunz commented on app-web/src/components/reservation/ReservationDialog.tsx
> +            닫기
수정했습니다.

2022-10-24 02:22 UTC, merged